# These are supported funding model platforms

github: longkunz
patreon: yamiannephilim
open_collective: longkunz
ko_fi: longkunz
tidelift: longkunz
community_bridge: longkunz
liberapay: longkunz
issuehunt: longkunz
otechie: longkunz
lfx_crowdfunding: longkunz
custom: paypal.me/yamiannephilim
